version: '3.9'
services:
  mariadb:
    image:  mariadb:latest
    networks:
      - mariadb
    volumes:
      - /data/mariadb:/data/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: cats_shop
      MARIADB_USER: root
      MARIADB_PASSWORD: admin
    ports:
      - "3306:3306"
  nestjs-api:
    image: nestjs-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - mariadb

networks:
  mariadb:
    driver: bridge



